##
## Copyright 2018 Marco Helmich
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

CarbonGrid:
  Cluster:
    RaftPort: 19191
    RaftServicePort: 18181
    SerfPort: 17171
    # default: ./db.carbon.grid/raft
    RaftStoreDir: "./db.carbon.grid/raft"
    # defaut: ./db.carbon.grid/serf
    SerfSnapshotPath: "./db.carbon.grid/serf"
    NumRaftVoters: 3

  Cache:
    # 1 KB
    MaxCacheLineSizeBytes: 1024
    # 1 GB
    MaxCacheSizeBytes: 1073741824
    # The maximum number of connections a cache holds
    # to other nodes in the cluster.
    # The more connections you hold, the faster communication
    # is when reusing connections.
    # The less connections you hold, the less memory and ports
    # you hold on to.
    MaxNumConnectionsToOtherNodes: 99
