// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache_comm.proto

/*
Package cache is a generated protocol buffer package.

It is generated from these files:
	cache_comm.proto

It has these top-level messages:
	LineId
	ClusterNodeId
	GetResponse
	GetsResponse
	GetxResponse
	Get
	Put
	Ack
	Gets
	Puts
	Getx
	Putx
	Inv
	InvAck
	ChangeOwner
	OwnerChanged
*/
package cache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OriginalMessageType int32

const (
	OriginalMessageType_GetMessageType  OriginalMessageType = 0
	OriginalMessageType_GetxMessageType OriginalMessageType = 1
)

var OriginalMessageType_name = map[int32]string{
	0: "GetMessageType",
	1: "GetxMessageType",
}
var OriginalMessageType_value = map[string]int32{
	"GetMessageType":  0,
	"GetxMessageType": 1,
}

func (x OriginalMessageType) String() string {
	return proto.EnumName(OriginalMessageType_name, int32(x))
}
func (OriginalMessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CacheError int32

const (
	CacheError_NoError CacheError = 0
	CacheError_Timeout CacheError = 1
)

var CacheError_name = map[int32]string{
	0: "NoError",
	1: "Timeout",
}
var CacheError_value = map[string]int32{
	"NoError": 0,
	"Timeout": 1,
}

func (x CacheError) String() string {
	return proto.EnumName(CacheError_name, int32(x))
}
func (CacheError) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CacheLineState int32

const (
	CacheLineState_Invalid   CacheLineState = 0
	CacheLineState_Exclusive CacheLineState = 1
	CacheLineState_Shared    CacheLineState = 2
	CacheLineState_Owned     CacheLineState = 3
)

var CacheLineState_name = map[int32]string{
	0: "Invalid",
	1: "Exclusive",
	2: "Shared",
	3: "Owned",
}
var CacheLineState_value = map[string]int32{
	"Invalid":   0,
	"Exclusive": 1,
	"Shared":    2,
	"Owned":     3,
}

func (x CacheLineState) String() string {
	return proto.EnumName(CacheLineState_name, int32(x))
}
func (CacheLineState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LineId struct {
	Time    uint64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Entropy []byte `protobuf:"bytes,2,opt,name=entropy,proto3" json:"entropy,omitempty"`
}

func (m *LineId) Reset()                    { *m = LineId{} }
func (m *LineId) String() string            { return proto.CompactTextString(m) }
func (*LineId) ProtoMessage()               {}
func (*LineId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LineId) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LineId) GetEntropy() []byte {
	if m != nil {
		return m.Entropy
	}
	return nil
}

type ClusterNodeId struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ClusterNodeId) Reset()                    { *m = ClusterNodeId{} }
func (m *ClusterNodeId) String() string            { return proto.CompactTextString(m) }
func (*ClusterNodeId) ProtoMessage()               {}
func (*ClusterNodeId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClusterNodeId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetResponse struct {
	// Types that are valid to be assigned to InnerMessage:
	//	*GetResponse_Put
	//	*GetResponse_OwnerChanged
	//	*GetResponse_Ack
	InnerMessage isGetResponse_InnerMessage `protobuf_oneof:"innerMessage"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isGetResponse_InnerMessage interface {
	isGetResponse_InnerMessage()
}

type GetResponse_Put struct {
	Put *Put `protobuf:"bytes,1,opt,name=put,oneof"`
}
type GetResponse_OwnerChanged struct {
	OwnerChanged *OwnerChanged `protobuf:"bytes,2,opt,name=ownerChanged,oneof"`
}
type GetResponse_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,oneof"`
}

func (*GetResponse_Put) isGetResponse_InnerMessage()          {}
func (*GetResponse_OwnerChanged) isGetResponse_InnerMessage() {}
func (*GetResponse_Ack) isGetResponse_InnerMessage()          {}

func (m *GetResponse) GetInnerMessage() isGetResponse_InnerMessage {
	if m != nil {
		return m.InnerMessage
	}
	return nil
}

func (m *GetResponse) GetPut() *Put {
	if x, ok := m.GetInnerMessage().(*GetResponse_Put); ok {
		return x.Put
	}
	return nil
}

func (m *GetResponse) GetOwnerChanged() *OwnerChanged {
	if x, ok := m.GetInnerMessage().(*GetResponse_OwnerChanged); ok {
		return x.OwnerChanged
	}
	return nil
}

func (m *GetResponse) GetAck() *Ack {
	if x, ok := m.GetInnerMessage().(*GetResponse_Ack); ok {
		return x.Ack
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetResponse_OneofMarshaler, _GetResponse_OneofUnmarshaler, _GetResponse_OneofSizer, []interface{}{
		(*GetResponse_Put)(nil),
		(*GetResponse_OwnerChanged)(nil),
		(*GetResponse_Ack)(nil),
	}
}

func _GetResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetResponse)
	// innerMessage
	switch x := m.InnerMessage.(type) {
	case *GetResponse_Put:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *GetResponse_OwnerChanged:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OwnerChanged); err != nil {
			return err
		}
	case *GetResponse_Ack:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ack); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetResponse.InnerMessage has unexpected type %T", x)
	}
	return nil
}

func _GetResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetResponse)
	switch tag {
	case 1: // innerMessage.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Put)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetResponse_Put{msg}
		return true, err
	case 2: // innerMessage.ownerChanged
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OwnerChanged)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetResponse_OwnerChanged{msg}
		return true, err
	case 3: // innerMessage.ack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ack)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetResponse_Ack{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetResponse)
	// innerMessage
	switch x := m.InnerMessage.(type) {
	case *GetResponse_Put:
		s := proto.Size(x.Put)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetResponse_OwnerChanged:
		s := proto.Size(x.OwnerChanged)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetResponse_Ack:
		s := proto.Size(x.Ack)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetsResponse struct {
	// Types that are valid to be assigned to InnerMessage:
	//	*GetsResponse_Puts
	//	*GetsResponse_OwnerChanged
	//	*GetsResponse_Ack
	InnerMessage isGetsResponse_InnerMessage `protobuf_oneof:"innerMessage"`
}

func (m *GetsResponse) Reset()                    { *m = GetsResponse{} }
func (m *GetsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetsResponse) ProtoMessage()               {}
func (*GetsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isGetsResponse_InnerMessage interface {
	isGetsResponse_InnerMessage()
}

type GetsResponse_Puts struct {
	Puts *Puts `protobuf:"bytes,1,opt,name=puts,oneof"`
}
type GetsResponse_OwnerChanged struct {
	OwnerChanged *OwnerChanged `protobuf:"bytes,2,opt,name=ownerChanged,oneof"`
}
type GetsResponse_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,oneof"`
}

func (*GetsResponse_Puts) isGetsResponse_InnerMessage()         {}
func (*GetsResponse_OwnerChanged) isGetsResponse_InnerMessage() {}
func (*GetsResponse_Ack) isGetsResponse_InnerMessage()          {}

func (m *GetsResponse) GetInnerMessage() isGetsResponse_InnerMessage {
	if m != nil {
		return m.InnerMessage
	}
	return nil
}

func (m *GetsResponse) GetPuts() *Puts {
	if x, ok := m.GetInnerMessage().(*GetsResponse_Puts); ok {
		return x.Puts
	}
	return nil
}

func (m *GetsResponse) GetOwnerChanged() *OwnerChanged {
	if x, ok := m.GetInnerMessage().(*GetsResponse_OwnerChanged); ok {
		return x.OwnerChanged
	}
	return nil
}

func (m *GetsResponse) GetAck() *Ack {
	if x, ok := m.GetInnerMessage().(*GetsResponse_Ack); ok {
		return x.Ack
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetsResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetsResponse_OneofMarshaler, _GetsResponse_OneofUnmarshaler, _GetsResponse_OneofSizer, []interface{}{
		(*GetsResponse_Puts)(nil),
		(*GetsResponse_OwnerChanged)(nil),
		(*GetsResponse_Ack)(nil),
	}
}

func _GetsResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetsResponse)
	// innerMessage
	switch x := m.InnerMessage.(type) {
	case *GetsResponse_Puts:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Puts); err != nil {
			return err
		}
	case *GetsResponse_OwnerChanged:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OwnerChanged); err != nil {
			return err
		}
	case *GetsResponse_Ack:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ack); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetsResponse.InnerMessage has unexpected type %T", x)
	}
	return nil
}

func _GetsResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetsResponse)
	switch tag {
	case 1: // innerMessage.puts
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Puts)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetsResponse_Puts{msg}
		return true, err
	case 2: // innerMessage.ownerChanged
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OwnerChanged)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetsResponse_OwnerChanged{msg}
		return true, err
	case 3: // innerMessage.ack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ack)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetsResponse_Ack{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetsResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetsResponse)
	// innerMessage
	switch x := m.InnerMessage.(type) {
	case *GetsResponse_Puts:
		s := proto.Size(x.Puts)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetsResponse_OwnerChanged:
		s := proto.Size(x.OwnerChanged)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetsResponse_Ack:
		s := proto.Size(x.Ack)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetxResponse struct {
	// Types that are valid to be assigned to InnerMessage:
	//	*GetxResponse_Putx
	//	*GetxResponse_OwnerChanged
	//	*GetxResponse_Ack
	InnerMessage isGetxResponse_InnerMessage `protobuf_oneof:"innerMessage"`
}

func (m *GetxResponse) Reset()                    { *m = GetxResponse{} }
func (m *GetxResponse) String() string            { return proto.CompactTextString(m) }
func (*GetxResponse) ProtoMessage()               {}
func (*GetxResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type isGetxResponse_InnerMessage interface {
	isGetxResponse_InnerMessage()
}

type GetxResponse_Putx struct {
	Putx *Putx `protobuf:"bytes,1,opt,name=putx,oneof"`
}
type GetxResponse_OwnerChanged struct {
	OwnerChanged *OwnerChanged `protobuf:"bytes,2,opt,name=ownerChanged,oneof"`
}
type GetxResponse_Ack struct {
	Ack *Ack `protobuf:"bytes,3,opt,name=ack,oneof"`
}

func (*GetxResponse_Putx) isGetxResponse_InnerMessage()         {}
func (*GetxResponse_OwnerChanged) isGetxResponse_InnerMessage() {}
func (*GetxResponse_Ack) isGetxResponse_InnerMessage()          {}

func (m *GetxResponse) GetInnerMessage() isGetxResponse_InnerMessage {
	if m != nil {
		return m.InnerMessage
	}
	return nil
}

func (m *GetxResponse) GetPutx() *Putx {
	if x, ok := m.GetInnerMessage().(*GetxResponse_Putx); ok {
		return x.Putx
	}
	return nil
}

func (m *GetxResponse) GetOwnerChanged() *OwnerChanged {
	if x, ok := m.GetInnerMessage().(*GetxResponse_OwnerChanged); ok {
		return x.OwnerChanged
	}
	return nil
}

func (m *GetxResponse) GetAck() *Ack {
	if x, ok := m.GetInnerMessage().(*GetxResponse_Ack); ok {
		return x.Ack
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetxResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetxResponse_OneofMarshaler, _GetxResponse_OneofUnmarshaler, _GetxResponse_OneofSizer, []interface{}{
		(*GetxResponse_Putx)(nil),
		(*GetxResponse_OwnerChanged)(nil),
		(*GetxResponse_Ack)(nil),
	}
}

func _GetxResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetxResponse)
	// innerMessage
	switch x := m.InnerMessage.(type) {
	case *GetxResponse_Putx:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Putx); err != nil {
			return err
		}
	case *GetxResponse_OwnerChanged:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OwnerChanged); err != nil {
			return err
		}
	case *GetxResponse_Ack:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ack); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetxResponse.InnerMessage has unexpected type %T", x)
	}
	return nil
}

func _GetxResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetxResponse)
	switch tag {
	case 1: // innerMessage.putx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Putx)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetxResponse_Putx{msg}
		return true, err
	case 2: // innerMessage.ownerChanged
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OwnerChanged)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetxResponse_OwnerChanged{msg}
		return true, err
	case 3: // innerMessage.ack
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ack)
		err := b.DecodeMessage(msg)
		m.InnerMessage = &GetxResponse_Ack{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetxResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetxResponse)
	// innerMessage
	switch x := m.InnerMessage.(type) {
	case *GetxResponse_Putx:
		s := proto.Size(x.Putx)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetxResponse_OwnerChanged:
		s := proto.Size(x.OwnerChanged)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetxResponse_Ack:
		s := proto.Size(x.Ack)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Get struct {
	SenderId int32   `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId `protobuf:"bytes,2,opt,name=lineId" json:"lineId,omitempty"`
}

func (m *Get) Reset()                    { *m = Get{} }
func (m *Get) String() string            { return proto.CompactTextString(m) }
func (*Get) ProtoMessage()               {}
func (*Get) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Get) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Get) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

type Put struct {
	Error    CacheError `protobuf:"varint,1,opt,name=error,enum=cache.CacheError" json:"error,omitempty"`
	SenderId int32      `protobuf:"varint,2,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId    `protobuf:"bytes,3,opt,name=lineId" json:"lineId,omitempty"`
	Version  int32      `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	Buffer   []byte     `protobuf:"bytes,5,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (m *Put) Reset()                    { *m = Put{} }
func (m *Put) String() string            { return proto.CompactTextString(m) }
func (*Put) ProtoMessage()               {}
func (*Put) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Put) GetError() CacheError {
	if m != nil {
		return m.Error
	}
	return CacheError_NoError
}

func (m *Put) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Put) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

func (m *Put) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Put) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type Ack struct {
	SenderId int32   `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId `protobuf:"bytes,2,opt,name=lineId" json:"lineId,omitempty"`
}

func (m *Ack) Reset()                    { *m = Ack{} }
func (m *Ack) String() string            { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()               {}
func (*Ack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Ack) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Ack) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

type Gets struct {
	SenderId int32   `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId `protobuf:"bytes,2,opt,name=lineId" json:"lineId,omitempty"`
}

func (m *Gets) Reset()                    { *m = Gets{} }
func (m *Gets) String() string            { return proto.CompactTextString(m) }
func (*Gets) ProtoMessage()               {}
func (*Gets) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Gets) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Gets) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

type Puts struct {
	Error    CacheError `protobuf:"varint,1,opt,name=error,enum=cache.CacheError" json:"error,omitempty"`
	SenderId int32      `protobuf:"varint,2,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId    `protobuf:"bytes,3,opt,name=lineId" json:"lineId,omitempty"`
	Version  int32      `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	Sharers  []int32    `protobuf:"varint,5,rep,packed,name=sharers" json:"sharers,omitempty"`
	Buffer   []byte     `protobuf:"bytes,6,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (m *Puts) Reset()                    { *m = Puts{} }
func (m *Puts) String() string            { return proto.CompactTextString(m) }
func (*Puts) ProtoMessage()               {}
func (*Puts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Puts) GetError() CacheError {
	if m != nil {
		return m.Error
	}
	return CacheError_NoError
}

func (m *Puts) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Puts) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

func (m *Puts) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Puts) GetSharers() []int32 {
	if m != nil {
		return m.Sharers
	}
	return nil
}

func (m *Puts) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type Getx struct {
	SenderId int32   `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId `protobuf:"bytes,2,opt,name=lineId" json:"lineId,omitempty"`
}

func (m *Getx) Reset()                    { *m = Getx{} }
func (m *Getx) String() string            { return proto.CompactTextString(m) }
func (*Getx) ProtoMessage()               {}
func (*Getx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Getx) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Getx) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

type Putx struct {
	Error    CacheError `protobuf:"varint,1,opt,name=error,enum=cache.CacheError" json:"error,omitempty"`
	SenderId int32      `protobuf:"varint,2,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId    `protobuf:"bytes,3,opt,name=lineId" json:"lineId,omitempty"`
	Version  int32      `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	Sharers  []int32    `protobuf:"varint,5,rep,packed,name=sharers" json:"sharers,omitempty"`
	Buffer   []byte     `protobuf:"bytes,6,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (m *Putx) Reset()                    { *m = Putx{} }
func (m *Putx) String() string            { return proto.CompactTextString(m) }
func (*Putx) ProtoMessage()               {}
func (*Putx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Putx) GetError() CacheError {
	if m != nil {
		return m.Error
	}
	return CacheError_NoError
}

func (m *Putx) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Putx) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

func (m *Putx) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Putx) GetSharers() []int32 {
	if m != nil {
		return m.Sharers
	}
	return nil
}

func (m *Putx) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type Inv struct {
	SenderId int32   `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId `protobuf:"bytes,2,opt,name=lineId" json:"lineId,omitempty"`
}

func (m *Inv) Reset()                    { *m = Inv{} }
func (m *Inv) String() string            { return proto.CompactTextString(m) }
func (*Inv) ProtoMessage()               {}
func (*Inv) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Inv) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *Inv) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

type InvAck struct {
	Error    CacheError `protobuf:"varint,1,opt,name=error,enum=cache.CacheError" json:"error,omitempty"`
	SenderId int32      `protobuf:"varint,2,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId    `protobuf:"bytes,3,opt,name=lineId" json:"lineId,omitempty"`
}

func (m *InvAck) Reset()                    { *m = InvAck{} }
func (m *InvAck) String() string            { return proto.CompactTextString(m) }
func (*InvAck) ProtoMessage()               {}
func (*InvAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *InvAck) GetError() CacheError {
	if m != nil {
		return m.Error
	}
	return CacheError_NoError
}

func (m *InvAck) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *InvAck) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

type ChangeOwner struct {
	SenderId int32   `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	LineId   *LineId `protobuf:"bytes,2,opt,name=lineId" json:"lineId,omitempty"`
	Version  int32   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Buffer   []byte  `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
}

func (m *ChangeOwner) Reset()                    { *m = ChangeOwner{} }
func (m *ChangeOwner) String() string            { return proto.CompactTextString(m) }
func (*ChangeOwner) ProtoMessage()               {}
func (*ChangeOwner) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ChangeOwner) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *ChangeOwner) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

func (m *ChangeOwner) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ChangeOwner) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type OwnerChanged struct {
	SenderId            int32               `protobuf:"varint,1,opt,name=senderId" json:"senderId,omitempty"`
	LineId              *LineId             `protobuf:"bytes,2,opt,name=lineId" json:"lineId,omitempty"`
	NewOwnerId          int32               `protobuf:"varint,3,opt,name=newOwnerId" json:"newOwnerId,omitempty"`
	OriginalMessageType OriginalMessageType `protobuf:"varint,4,opt,name=originalMessageType,enum=cache.OriginalMessageType" json:"originalMessageType,omitempty"`
}

func (m *OwnerChanged) Reset()                    { *m = OwnerChanged{} }
func (m *OwnerChanged) String() string            { return proto.CompactTextString(m) }
func (*OwnerChanged) ProtoMessage()               {}
func (*OwnerChanged) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *OwnerChanged) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *OwnerChanged) GetLineId() *LineId {
	if m != nil {
		return m.LineId
	}
	return nil
}

func (m *OwnerChanged) GetNewOwnerId() int32 {
	if m != nil {
		return m.NewOwnerId
	}
	return 0
}

func (m *OwnerChanged) GetOriginalMessageType() OriginalMessageType {
	if m != nil {
		return m.OriginalMessageType
	}
	return OriginalMessageType_GetMessageType
}

func init() {
	proto.RegisterType((*LineId)(nil), "cache.LineId")
	proto.RegisterType((*ClusterNodeId)(nil), "cache.ClusterNodeId")
	proto.RegisterType((*GetResponse)(nil), "cache.GetResponse")
	proto.RegisterType((*GetsResponse)(nil), "cache.GetsResponse")
	proto.RegisterType((*GetxResponse)(nil), "cache.GetxResponse")
	proto.RegisterType((*Get)(nil), "cache.Get")
	proto.RegisterType((*Put)(nil), "cache.Put")
	proto.RegisterType((*Ack)(nil), "cache.Ack")
	proto.RegisterType((*Gets)(nil), "cache.Gets")
	proto.RegisterType((*Puts)(nil), "cache.Puts")
	proto.RegisterType((*Getx)(nil), "cache.Getx")
	proto.RegisterType((*Putx)(nil), "cache.Putx")
	proto.RegisterType((*Inv)(nil), "cache.Inv")
	proto.RegisterType((*InvAck)(nil), "cache.InvAck")
	proto.RegisterType((*ChangeOwner)(nil), "cache.ChangeOwner")
	proto.RegisterType((*OwnerChanged)(nil), "cache.OwnerChanged")
	proto.RegisterEnum("cache.OriginalMessageType", OriginalMessageType_name, OriginalMessageType_value)
	proto.RegisterEnum("cache.CacheError", CacheError_name, CacheError_value)
	proto.RegisterEnum("cache.CacheLineState", CacheLineState_name, CacheLineState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CacheComm service

type CacheCommClient interface {
	Get(ctx context.Context, in *Get, opts ...grpc.CallOption) (*GetResponse, error)
	Gets(ctx context.Context, in *Gets, opts ...grpc.CallOption) (*GetsResponse, error)
	Getx(ctx context.Context, in *Getx, opts ...grpc.CallOption) (*GetxResponse, error)
	Invalidate(ctx context.Context, in *Inv, opts ...grpc.CallOption) (*InvAck, error)
}

type cacheCommClient struct {
	cc *grpc.ClientConn
}

func NewCacheCommClient(cc *grpc.ClientConn) CacheCommClient {
	return &cacheCommClient{cc}
}

func (c *cacheCommClient) Get(ctx context.Context, in *Get, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/cache.CacheComm/get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheCommClient) Gets(ctx context.Context, in *Gets, opts ...grpc.CallOption) (*GetsResponse, error) {
	out := new(GetsResponse)
	err := grpc.Invoke(ctx, "/cache.CacheComm/gets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheCommClient) Getx(ctx context.Context, in *Getx, opts ...grpc.CallOption) (*GetxResponse, error) {
	out := new(GetxResponse)
	err := grpc.Invoke(ctx, "/cache.CacheComm/getx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheCommClient) Invalidate(ctx context.Context, in *Inv, opts ...grpc.CallOption) (*InvAck, error) {
	out := new(InvAck)
	err := grpc.Invoke(ctx, "/cache.CacheComm/invalidate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CacheComm service

type CacheCommServer interface {
	Get(context.Context, *Get) (*GetResponse, error)
	Gets(context.Context, *Gets) (*GetsResponse, error)
	Getx(context.Context, *Getx) (*GetxResponse, error)
	Invalidate(context.Context, *Inv) (*InvAck, error)
}

func RegisterCacheCommServer(s *grpc.Server, srv CacheCommServer) {
	s.RegisterService(&_CacheComm_serviceDesc, srv)
}

func _CacheComm_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Get)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheCommServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.CacheComm/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheCommServer).Get(ctx, req.(*Get))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheComm_Gets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gets)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheCommServer).Gets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.CacheComm/Gets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheCommServer).Gets(ctx, req.(*Gets))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheComm_Getx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Getx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheCommServer).Getx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.CacheComm/Getx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheCommServer).Getx(ctx, req.(*Getx))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheComm_Invalidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Inv)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheCommServer).Invalidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cache.CacheComm/Invalidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheCommServer).Invalidate(ctx, req.(*Inv))
	}
	return interceptor(ctx, in, info, handler)
}

var _CacheComm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cache.CacheComm",
	HandlerType: (*CacheCommServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _CacheComm_Get_Handler,
		},
		{
			MethodName: "gets",
			Handler:    _CacheComm_Gets_Handler,
		},
		{
			MethodName: "getx",
			Handler:    _CacheComm_Getx_Handler,
		},
		{
			MethodName: "invalidate",
			Handler:    _CacheComm_Invalidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache_comm.proto",
}

func init() { proto.RegisterFile("cache_comm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0xb5, 0xe3, 0x8f, 0xbe, 0x5e, 0x27, 0x79, 0x7e, 0x13, 0xe9, 0xc9, 0xca, 0xa2, 0x14, 0x4b,
	0xd0, 0x92, 0x45, 0x17, 0x41, 0x42, 0x62, 0x83, 0x54, 0xa2, 0x2a, 0xb1, 0x54, 0x4a, 0xe5, 0x76,
	0x8f, 0x5c, 0xfb, 0x36, 0xb5, 0x92, 0x8c, 0xa3, 0x99, 0x71, 0xea, 0x6e, 0xf9, 0x15, 0x2c, 0xd8,
	0xf1, 0x23, 0xd8, 0xc1, 0x5f, 0x43, 0x33, 0xb1, 0x1b, 0x87, 0xb6, 0xac, 0xa2, 0x02, 0x9b, 0x68,
	0xee, 0xdc, 0x33, 0x67, 0xce, 0x3d, 0xbe, 0xbe, 0x0e, 0xb8, 0x71, 0x14, 0x5f, 0xe1, 0x87, 0x38,
	0x9b, 0xcd, 0x0e, 0xe6, 0x2c, 0x13, 0x19, 0xb1, 0xd4, 0x8e, 0xff, 0x0a, 0xec, 0xe3, 0x94, 0x62,
	0x90, 0x10, 0x02, 0xa6, 0x48, 0x67, 0xe8, 0xe9, 0xbb, 0xfa, 0xbe, 0x19, 0xaa, 0x35, 0xf1, 0x60,
	0x0b, 0xa9, 0x60, 0xd9, 0xfc, 0xc6, 0x6b, 0xec, 0xea, 0xfb, 0xcd, 0xb0, 0x0a, 0xfd, 0x27, 0xd0,
	0x1a, 0x4c, 0x73, 0x2e, 0x90, 0x9d, 0x64, 0x89, 0x3c, 0xde, 0x86, 0x46, 0x9a, 0xa8, 0xc3, 0x56,
	0xd8, 0x48, 0x13, 0xff, 0x93, 0x0e, 0xce, 0x10, 0x45, 0x88, 0x7c, 0x9e, 0x51, 0x8e, 0x64, 0x07,
	0x8c, 0x79, 0x2e, 0x14, 0xc0, 0xe9, 0xc3, 0x81, 0xba, 0xfd, 0xe0, 0x34, 0x17, 0x23, 0x2d, 0x94,
	0x09, 0xf2, 0x1a, 0x9a, 0xd9, 0x35, 0x45, 0x36, 0xb8, 0x8a, 0xe8, 0x18, 0x13, 0x75, 0x9f, 0xd3,
	0xef, 0x94, 0xc0, 0xf7, 0xb5, 0xd4, 0x48, 0x0b, 0xd7, 0xa0, 0x92, 0x3a, 0x8a, 0x27, 0x9e, 0xb1,
	0x46, 0x7d, 0x18, 0x4f, 0x24, 0x75, 0x14, 0x4f, 0xde, 0xb6, 0xa1, 0x99, 0x52, 0x8a, 0xec, 0x1d,
	0x72, 0x1e, 0x8d, 0xd1, 0xff, 0xac, 0x43, 0x73, 0x88, 0x82, 0xdf, 0x6a, 0x7b, 0x0a, 0xe6, 0x3c,
	0x17, 0xbc, 0x14, 0xe7, 0xac, 0xc4, 0xf1, 0x91, 0x16, 0xaa, 0xd4, 0x6f, 0x90, 0x57, 0xfc, 0x24,
	0xaf, 0xb8, 0x2b, 0xaf, 0x28, 0xe5, 0x15, 0x8f, 0x29, 0x6f, 0x04, 0xc6, 0x10, 0x05, 0xe9, 0xc2,
	0x3f, 0x1c, 0x69, 0x82, 0x2c, 0xa8, 0x9e, 0xfa, 0x6d, 0x4c, 0x9e, 0x81, 0x3d, 0x55, 0x4d, 0x55,
	0xea, 0x68, 0x95, 0xac, 0xcb, 0x4e, 0x0b, 0xcb, 0xa4, 0xff, 0x45, 0x07, 0xe3, 0x34, 0x17, 0x64,
	0x0f, 0x2c, 0x64, 0x2c, 0x63, 0x8a, 0xa7, 0xdd, 0xff, 0xaf, 0x44, 0x0f, 0xe4, 0xef, 0x91, 0x4c,
	0x84, 0xcb, 0xfc, 0xda, 0x9d, 0x8d, 0x07, 0xef, 0x34, 0x7e, 0x71, 0xa7, 0xec, 0xe8, 0x05, 0x32,
	0x9e, 0x66, 0xd4, 0x33, 0x15, 0x43, 0x15, 0x92, 0xff, 0xc1, 0xbe, 0xc8, 0x2f, 0x2f, 0x91, 0x79,
	0x96, 0x6a, 0xf5, 0x32, 0x92, 0xf5, 0x1e, 0xc6, 0x93, 0x4d, 0xd4, 0x1b, 0x80, 0x29, 0xdb, 0x6e,
	0x13, 0x54, 0xdf, 0x74, 0x30, 0x65, 0x7f, 0xfe, 0x21, 0xde, 0x79, 0xb0, 0xc5, 0xaf, 0x22, 0x86,
	0x8c, 0x7b, 0xd6, 0xae, 0x21, 0x33, 0x65, 0x58, 0x73, 0xd5, 0x5e, 0x73, 0x75, 0xe9, 0x45, 0xb1,
	0x41, 0x2f, 0x8a, 0xbf, 0xd6, 0x8b, 0x11, 0x18, 0x01, 0x5d, 0x6c, 0xc2, 0x0a, 0x01, 0x76, 0x40,
	0x17, 0xb2, 0x5d, 0x1f, 0xd1, 0x0b, 0xff, 0xa3, 0x0e, 0xce, 0x72, 0x9a, 0xa8, 0x41, 0xb3, 0x81,
	0x42, 0xea, 0xf6, 0x1a, 0x0f, 0xbd, 0xa6, 0xe6, 0x9a, 0x89, 0xdf, 0x75, 0x68, 0xd6, 0xe7, 0xdc,
	0x26, 0x54, 0xec, 0x00, 0x50, 0xbc, 0x56, 0xac, 0xa5, 0x07, 0x56, 0x58, 0xdb, 0x21, 0xc7, 0xd0,
	0xc9, 0x58, 0x3a, 0x4e, 0x69, 0x34, 0x2d, 0xa7, 0xe3, 0xf9, 0xcd, 0x1c, 0x95, 0xb0, 0x76, 0xbf,
	0x5b, 0x0d, 0xdf, 0xbb, 0x88, 0xf0, 0xbe, 0x63, 0xbd, 0x37, 0xd0, 0xb9, 0x07, 0x4b, 0x08, 0xb4,
	0x87, 0x28, 0x6a, 0x3b, 0xae, 0x46, 0x3a, 0xf0, 0xaf, 0x7c, 0x7b, 0xea, 0x9b, 0x7a, 0xef, 0x39,
	0xc0, 0xea, 0xf1, 0x12, 0x07, 0xb6, 0x4e, 0x32, 0xb5, 0x74, 0x35, 0x19, 0x9c, 0xa7, 0x33, 0xcc,
	0x72, 0xe1, 0xea, 0xbd, 0x01, 0xb4, 0x15, 0x4e, 0x16, 0x7b, 0x26, 0x22, 0x81, 0x32, 0x1d, 0xd0,
	0x45, 0x34, 0x4d, 0x13, 0x57, 0x23, 0x2d, 0xd8, 0x3e, 0x2a, 0xe2, 0x69, 0xce, 0xd3, 0x05, 0xba,
	0x3a, 0x01, 0xb0, 0xcf, 0x64, 0xff, 0x26, 0x6e, 0x83, 0x6c, 0x83, 0x25, 0x4b, 0x4f, 0x5c, 0xa3,
	0xff, 0x55, 0x87, 0x6d, 0xc5, 0x32, 0xc8, 0x66, 0x33, 0xb2, 0x07, 0xc6, 0x18, 0x05, 0xa9, 0xbe,
	0x1e, 0x43, 0x14, 0x5d, 0xb2, 0x5a, 0x57, 0x1f, 0x32, 0x5f, 0x23, 0x3d, 0x30, 0xc7, 0x72, 0x04,
	0x3a, 0xab, 0x2c, 0xef, 0x76, 0x6a, 0xc1, 0x1d, 0x6c, 0x51, 0xc7, 0x16, 0x75, 0x6c, 0x51, 0xc3,
	0xbe, 0x00, 0x48, 0x97, 0x15, 0xc8, 0x7a, 0x2a, 0x1d, 0x01, 0x5d, 0x74, 0x5b, 0xab, 0xf5, 0x61,
	0x3c, 0xf1, 0xb5, 0x0b, 0x5b, 0xfd, 0xff, 0x79, 0xf9, 0x23, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x5f,
	0xe2, 0x0a, 0x13, 0x09, 0x00, 0x00,
}
